version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
        environment:
          RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install QT Webkit
          command:
            - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
            - sudo apt-get -y update; true
            - sudo apt-get -y install libqtwebkit-dev libqtwebkit4

      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle

      - run:
          name: Run Specs
          command: bundle exec rspec --format progress --profile 10 spec

  deploy:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
        environment:
          RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
