version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-browsers
        environment:
          RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: Install QT Webkit
          command: sudo apt-get -y install libqt5webkit5-dev libqt5webkit5

      - run:
          name: Update Gems
          command: sudo gem update --system

      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Specs
          command: bundle exec rspec --format progress --profile 10 spec

  deploy:
    docker:
      - image: cimg/ruby:2.7-browsers
        environment:
          RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: Deploy to fly.io
          command: |
            apk add --no-cache curl
            curl -L https://fly.io/install.sh | sh
            export FLYCTL_INSTALL="/root/.fly"
            export PATH="$FLYCTL_INSTALL/bin:$PATH"
            sh -c "flyctl deploy"
            sh -c "flyctl info"
            exit 0

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
