version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.6-ram
        environment:
          MYSQL_DATABASE: phillip_boksz_test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: "%"

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle

      - run:
          name: Create and  Load Database
          command: bundle exec rake db:create db:schema:load

      - run:
          name: Run Specs
          command: bundle exec rspec --format progress --profile 10 spec

  deploy:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
        environment:
          RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
